16272: Updated stitch vs-code extension to validate and auto-complete *.integration.yaml files
ShipitSmarter/vscode-stitch pull request #30
Opened 2023-05-16 14:18 UTC by Droxx

This addresses work item 16272, it applies the existing *.integration.json schema to *.integration.yaml files.

Note: the contributes hook I used 'yamlValidation' is not supported natively by vscode. To use auto-complete in YAML files. Users will have to download the [YAML extension.](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml).

![16272](https://github.com/ShipitSmarter/vscode-stitch/assets/7061710/3fbe710f-4d30-4ee8-b518-eafd798ac3a7)

2023-05-22 07:37 UTC, Droxx commented
@ThumNet 

This is the PR for stitch vs-code app. Containing work from https://dev.azure.com/shipitsmarterdev/CurrentPlatform/_workitems/edit/16271 & https://dev.azure.com/shipitsmarterdev/CurrentPlatform/_workitems/edit/16325

2023-05-22 07:42 UTC, ThumNet requested changes
Let's discuss the .yml extension

2023-05-22 07:42 UTC, ThumNet commented on package.json
> +					"when": "stitch:contextAvailable || resourceFilename =~ /.integration.json$/ || resourceFilename =~ /.integration.yaml$/"
Don't we need to support .yml as well?

Might want to use a regex like .(json|yml|yaml)$ then :)

2023-05-22 07:42 UTC, ThumNet commented on src/StitchPreview.ts
> +                title: `No ${CONSTANTS.integrationExtensionJson} or ${CONSTANTS.integrationExtensionYaml} file found`,
Should this also contain the yml extension and then we might need to change the entire message.

2023-05-22 07:42 UTC, ThumNet commented on src/constants.ts
> +    integrationExtensionYaml: '.integration.yaml',
.yml ?

2023-05-22 07:42 UTC, ThumNet commented on src/utils/helpers.ts
> +    const jsonChars = ['{', '{'];
Should be { and [ right?

2023-05-23 07:01 UTC, Droxx commented
@ThumNet Addressed your feedback for this PR

I also enforced PascalCase for YAML files

2023-05-23 13:55 UTC, ThumNet requested changes
1 small change still needed

2023-05-23 13:55 UTC, ThumNet commented on package.json
> +					"when": "stitch:contextAvailable || resourceFilename =~ /.integration.((json|yaml|yml))$/"
Double braces are not needed here

2023-05-23 13:56 UTC, ThumNet approved these changes

2023-05-23 13:59 UTC, merged